#' Create a list of issues in a GitHub repo
#'
#' @param owner The owner of the repo, e.g. `ropensci`
#' @param repo The name of the repo, e.g. `gh`
#' @param state One of `"all"` (the default), `"open"`, or `"closed"`
#' @param limit Maximum number of issues to return, `Inf` by default
#' @export
#' @examples
#' owner = "ATFutures"
#' repo = "who3"
#' gg_issue_list(owner, repo, limit = 2)
gg_issue_list = function(owner, repo, state = "all", limit = Inf) {
  issue_list = gh::gh("/repos/:owner/:repo/issues", owner = owner, repo = repo, state = "all", .limit = limit)
  message(length(issue_list), " issues returned for the repo ", repo)
  issue_list
}
#' Covert a list of issues into a data frame
#' @param issue_list A list of issues generated by `gg_issue_list`
#' @export
#' @examples
#' owner = "ATFutures"
#' repo = "who3"
#' issue_list = gg_issue_list(owner, repo, limit = 2)
#' gg_issue_df(issue_list)
gg_issue_df = function(issue_list) {
  tibble::tibble(
        number = purrr::map_int(issue_list, "number"),
        title = purrr::map_chr(issue_list, "title"),
        description = purrr::map_chr(issue_list, "body"),
        state = purrr::map_chr(issue_list, "state"),
        created_at = as.Date(purrr::map_chr(issue_list, "created_at"))
  )
}

#' Extract dates from gh issues
#'
#' @param issue_body The body of an issue that contains `GanttStart` and `GanttDue` lines
#' @param pattern The text string used to identify start and due dates
#' @export
#' @examples
#' issue_body = "GanttStart: 2019-09-01\r\nGanttDue: 2019-10-01"
#' gg_extract_dates(issue_body)
#' gg_start_date(issue_body)
#' gg_due_date(issue_body)
gg_extract_dates = function(issue_body, pattern = "GanttStart: |GanttDue: ") {
  body_lines = stringi::stri_split_lines1(issue_body)
  body_date_strings = body_lines[grepl(pattern = pattern, body_lines)]
  as.Date(gsub(pattern = pattern, replacement = "", body_date_strings))
}
#' @rdname gg_extract_dates
#' @export
gg_start_date = function(issue_body) {
  gg_extract_dates(issue_body, pattern = "GanttStart: ")
}
#' @rdname gg_extract_dates
#' @export
gg_due_date = function(issue_body) {
  gg_extract_dates(issue_body, pattern = "GanttDue: ")
}
# # code to extract start times ---------------------------------------------
#
# task_df$description[1]
# stringi::stri_split_lines(task_df$description[1])
# stringi::stri_split_lines(task_df$description[1])[[1]]
# stringi::stri_split_lines1(task_df$description[1])
#
# extract_start_date = function(x) {
#
# }
